config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects', include('projects.urls')),
    path('', include('users.urls')),

    # View to handle password reset

    path('reset-password/',
         auth_views.PasswordResetView.as_view(template_name='reset_password.html'),
         name='reset_password'),

    path('password-reset-sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='reset_password_sent.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='reset.html'),
         name='password_reset_confirm'),

    path('reset-password-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='reset_password_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_user, name='register'),

    path('', views.profiles, name='profiles'),
    path('profile/<str:username>/', views.user_profile, name='user_profile'),
    path('account/', views.user_account, name='account'),
    path('edit-account', views.edit_account, name='edit_account'),
    path('create-skill/', views.create_skill, name='create_skill'),
    path('update-skill/<pk>/', views.update_skill, name='update_skill'),
    path('delete-skill/<pk>/', views.delete_skill, name='delete_skill'),

    path('inbox/', views.inbox, name='inbox'),
    path('message/<pk>/', views.view_message, name='view_message'),
    path('send-message/<pk>/', views.send_message, name='send_message'),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile

UP_VOTE = 'up'
DOWN_VOTE = 'down'


class BaseModelMixin(models.Model):
    """
        Base model mixin to create 'created' and 'id' field for all models
    """
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        abstract = True


class Project(BaseModelMixin, models.Model):
    """
        Project Model, to store information related to each project
    """
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default='default.jpg')
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)

    @property
    def reviewers(self):
        """Getting all reviewers that voted this project"""
        return self.review_set.all().values_list('owner__id', flat=True)

    @property
    def get_vote_count(self):
        """getting total number of votes"""
        reviews = self.review_set.all()
        up_votes = reviews.filter(value=UP_VOTE).count()
        total_votes = reviews.count()

        ration = (up_votes / total_votes) * 100
        self.vote_total = total_votes
        self.vote_ratio = ration
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-vote_ratio', '-vote_total', 'title')


class Review(BaseModelMixin, models.Model):
    """
        Review model, to store project reviews
    """

    VOTE_TYPE = (
        (UP_VOTE, 'Up Vote'),
        (DOWN_VOTE, 'Down Vote'),
    )

    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)

    def __str__(self):
        return self.value

    class Meta:
        unique_together = [['owner', 'project']]


class Tag(BaseModelMixin, models.Model):
    """
        Tag model, to store project tags
    """
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

users/models.py
import uuid
from django.db import models
from django.conf import settings


class BaseModelMixin(models.Model):
    """
        Base model mixin to create 'created' and 'id' field for all models
    """
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        abstract = True


class Profile(BaseModelMixin, models.Model):
    """
        Profile model to store profiles
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=200, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(blank=True, null=True, upload_to='profiles/',
                                      default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return str(self.user.username)


class Skill(BaseModelMixin, models.Model):
    """
        Skill model to store user skills
    """
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.name)


class Message(BaseModelMixin, models.Model):
    """
        Message model to store messages for each user
    """
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True,
                                  blank=True, related_name='messages')
    is_read = models.BooleanField(default=False, null=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()

    def __str__(self):
        return f"{self.subject}"

    class Meta:
        ordering = ('is_read', '-created',)

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Profile, Skill, Message

User = get_user_model()


class StyleFormMixin:
    """Mixin to style fields input"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update(
                {'class': 'input'})


class CustomerUserCreationForm(StyleFormMixin, UserCreationForm):
    """
        Custom user creation form
    """

    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name'
        }


class ProfileForm(StyleFormMixin, ModelForm):
    """
        Model Form to edit profile
    """

    class Meta:
        model = Profile
        fields = ['name', 'username', 'email', 'location', 'short_intro', 'bio',
                  'profile_image', 'social_github', 'social_linkedin', 'social_twitter',
                  'social_youtube', 'social_website']


class SkillForm(StyleFormMixin, ModelForm):
    """
        Model form to Create and Edit Skill
    """

    class Meta:
        model = Skill
        fields = '__all__'
        exclude = ['owner']


class MessageForm(StyleFormMixin, ModelForm):
    """
        Model form to Create Message
    """

    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.conf import settings
from .utils import search_profile, paginate_profiles
from .models import Profile, Skill, Message
from .forms import CustomerUserCreationForm, ProfileForm, SkillForm, MessageForm

User = get_user_model()


def login_view(request):
    """Temporary view to login the user"""
    context = {'page': 'login'}
    if request.method == 'POST':
        username, password = request.POST['username'], request.POST['password']
        if User.objects.filter(username=username).exists():
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                if 'next' in request.GET:
                    return redirect(request.GET['next'])
                return redirect('account')
            else:
                messages.error(request, 'The credentials are wrong!')
        else:
            messages.error(request, 'This user does not exist!')
    return render(request, 'users/login_register.html', context)


def logout_view(request):
    """View to Logout """
    logout(request)
    messages.info(request, 'User was successfully logged out!')
    return redirect('login')


def register_user(request):
    """View to register users"""
    if request.method == 'POST':
        form = CustomerUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'user account was successfully created')
            login(request, user)
            return redirect('edit_account')
    else:
        form = CustomerUserCreationForm()

    context = {'page': 'register', 'form': form}
    return render(request, 'users/login_register.html', context)


def profiles(request):
    """Renders all profiles"""
    profiles_, search_query = search_profile(request)
    profiles_, custom_range = paginate_profiles(request,
                                                profiles_,
                                                settings.PROFILE_PER_PAGE)

    return render(request, 'users/profiles.html', {'profiles': profiles_,
                                                   'custom_range': custom_range,
                                                   'search_query': search_query})


def user_profile(request, username):
    """Render user profile"""
    profile = get_object_or_404(Profile, user__username=username)
    top_skills = profile.skill_set.exclude(description__exact='')
    other_skills = profile.skill_set.filter(description='')
    context = {'profile': profile,
               'top_skills': top_skills,
               'other_skills': other_skills}
    return render(request, 'users/user-profile.html', context)


@login_required
def user_account(request):
    """Render user account"""
    profile = request.user.profile
    context = {'profile': profile}
    return render(request, 'users/account.html', context)


@login_required
def edit_account(request):
    """View to edit user profile"""
    profile = request.user.profile

    if request.method == 'POST':
        form = ProfileForm(instance=profile,
                           data=request.POST,
                           files=request.FILES)

        if form.is_valid():
            form.save()
            return redirect('account')
        else:
            messages.error(request, form.errors)
    else:
        form = ProfileForm(instance=profile)

    context = {'form': form}

    return render(request, 'users/profile_form.html', context)


@login_required
def create_skill(request):
    """View to create a skill"""
    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = request.user.profile
            skill.save()
            messages.success(request, 'Skill was created successfully')
            return redirect('account')
        else:
            messages.error(request, form.errors)
    else:
        form = SkillForm()

    context = {"form": form}
    return render(request, 'users/skill_form.html', context)


@login_required
def update_skill(request, pk):
    """View to update a skill"""
    profile = request.user.profile
    skill = get_object_or_404(Skill, id=pk, owner=profile)
    if request.method == 'POST':
        form = SkillForm(instance=skill, data=request.POST)
        if form.is_valid():
            skill.save()
            messages.success(request, 'Skill was updated successfully')
            return redirect('account')
        else:
            messages.error(request, form.errors)
    else:
        form = SkillForm(instance=skill)

    context = {"form": form}
    return render(request, 'users/skill_form.html', context)


@login_required
def delete_skill(request, pk):
    """View to delete the skill"""
    profile = request.user.profile
    skill = get_object_or_404(Skill, id=pk, owner=profile)
    if request.method == 'POST':
        skill.delete()
        messages.success(request, 'Skill was deleted successfully')
        return redirect('account')
    return render(request, 'delete_object.html', context={'object': skill})


@login_required
def inbox(request):
    """View to show messages of each user"""
    profile = request.user.profile
    inbox_messages = profile.messages.all()
    unread_messages = profile.messages.filter(is_read=False).count()
    context = {'inbox_messages': inbox_messages, 'unread_messages': unread_messages}
    return render(request, 'users/inbox.html', context)


@login_required
def view_message(request, pk):
    """View to see messages"""
    message = get_object_or_404(Message,
                                id=pk,
                                recipient=request.user.profile)
    message.is_read = True
    message.save()
    return render(request, 'users/message.html', {'message': message})


def send_message(request, pk):
    """Send message to a user"""
    profile = get_object_or_404(Profile, id=pk)

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            if request.user.is_authenticated:
                message.sender = request.user.profile
            message.recipient = profile
            message.save()
            messages.success(request,'Message was successfully sent!')
            return redirect('user_profile', profile.user.username)
        else:
            messages.error(request, form.errors)
    else:
        form = MessageForm()

    context = {'profile': profile, 'form': form}
    return render(request, 'users/message_form.html', context)

users/templates/users/account.html
{% extends 'main.html' %}
{% load static %}
<!-- Main Section -->
{% block content %}
    <main class="settingsPage profile my-md">
        <div class="container">
            <div class="layout">
                <div class="column column--1of3">
                    <div class="card text-center">
                        <div class="card__body dev">
                            <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit_account' %}"><i class="im im-edit"></i>
                                Edit</a>
                            <img class="avatar avatar--xl dev__avatar"
                                 src="{{ profile.profile_image.url }}"/>
                            <h2 class="dev__name">{{ profile.name }}</h2>
                            <p class="dev__title">{{ profile.short_intro }}</p>
                            <p class="dev__location">{{ profile.location }}</p>
                            <ul class="dev__social">
                                {% if profile.social_github %}
                                    <li>
                                        <a title="Github" href="{{ profile.social_github }}" target="_blank"><i
                                                class="im im-github"></i></a>
                                    </li>
                                {% endif %}

                                {% if profile.social_twitter %}

                                    <li>
                                        <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i
                                                class="im im-twitter"></i></a>
                                    </li>
                                {% endif %}


                                {% if profile.social_linkedin %}
                                    <li>
                                        <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i
                                                class="im im-linkedin"></i></a>
                                    </li>
                                {% endif %}

                                {% if profile.social_youtube %}
                                    <li>
                                        <a title="YouTube" href="{{ profile.social_linkedin }}" target="_blank"><i
                                                class="im im-youtube"></i></a>
                                    </li>
                                {% endif %}


                                {% if profile.social_website %}
                                    <li>
                                        <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i
                                                class="im im-globe"></i></a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="column column--2of3">
                    <div class="devInfo">
                        <h3 class="devInfo__title">About Me</h3>
                        <p class="devInfo__about">{{ profile.bio }}</p>
                    </div>
                    <div class="settings">
                        <h3 class="settings__title">Skills</h3>
                        <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create_skill' %}">
                            <i class="im im-plus"></i> Add
                            Skill</a>
                    </div>

                    <table class="settings__table">

                        {% for skill in profile.skill_set.all %}
                            <tr>
                                <td class="settings__tableInfo">
                                    <h4>{{ skill }}</h4>
                                    <p>{{ skill.description }}</p>
                                </td>
                                <td class="settings__tableActions">
                                    <a class="tag tag--pill tag--main settings__btn" href="{% url 'update_skill' skill.id %}">
                                        <i class="im im-edit"></i>
                                        Edit</a>
                                    <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete_skill' skill.id %}?next=/account"><i
                                            class="im im-x-mark-circle-o"></i>
                                        Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>

                    <div class="settings">
                        <h3 class="settings__title">Projects</h3>
                        <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create_project' %}">
                            <i class="im im-plus"></i> Add Project</a>
                    </div>

                    <table class="settings__table">
                        {% for project in profile.project_set.all %}
                            <tr>
                                <td class="settings__thumbnail">
                                    <a href="{% url 'project' project.id %}"><img src="{{ project.featured_image.url }}"
                                                                                  alt="Project Thumbnail"/></a>
                                </td>
                                <td class="settings__tableInfo">
                                    <a href="{% url 'project' project.id %}">{{ project }}</a>
                                    <p>{{ project.description|slice:"150" }}</p>
                                </td>
                                <td class="settings__tableActions">
                                    <a class="tag tag--pill tag--main settings__btn" href="{% url 'update_project' project.id %}">
                                        <i class="im im-edit"></i>
                                        Edit</a>
                                    <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete_project' project.id %}?next=/account"><i
                                            class="im im-x-mark-circle-o"></i>
                                        Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}
    <!-- Main Section -->
    <main class="inbox my-xl">
        <div class="content-box">
            <h3 class="inbox__title">New Messages(<span>{{ unread_messages }}</span>)</h3>
            <ul class="messages">
                {% for message in inbox_messages %}
                    <li class="message {% if message.is_read == False %}message--unread{% endif %}">
                        <a href="{% url 'view_message' message.id %}">
                    <span class="message__author">
                        {% if message.name %}
                            {{ message.name }}
                        {% elif message.sender %}
                            {{ message.sender }}
                        {% else %}
                            Unanonymouse
                        {% endif %}
                    </span>
                            {% if message.subject %}
                                <span class="message__subject">{{ message.subject }}</span>
                            {% else %}
                                <span class="message__subject"></span>
                            {% endif %}
                            <span class="message__date">{{ message.created }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </main>
{% endblock %}

users/templates/users/skill_form.html
{% extends 'main.html' %}

{% block content %}
    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form__field">
                            <label for="formInput#text">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit"/>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}
    <!-- Main Section -->
    <main class="profile my-md">
        <div class="container">
            <div class="layout">
                <div class="column column--1of3">
                    <div class="card text-center">
                        <div class="card__body dev">
                            <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}"/>
                            <h2 class="dev__name">{{ profile.name }}</h2>
                            <p class="dev__title">{{ profile.short_intro }}</p>
                            <p class="dev__location">Based in {{ profile.location }}</p>
                            <ul class="dev__social">
                                {% if profile.social_github %}
                                    <li>
                                        <a title="Github" href="{{ profile.social_github }}" target="_blank"><i
                                                class="im im-github"></i></a>
                                    </li>
                                {% endif %}

                                {% if profile.social_twitter %}
                                    <li>
                                        <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i
                                                class="im im-twitter"></i></a>
                                    </li>
                                {% endif %}

                                {% if profile.social_linkedin %}
                                    <li>
                                        <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                                    </li>
                                {% endif %}

                                {% if profile.social_youtube %}
                                    <li>
                                        <a title="Youtube" href="#" target="_blank"><i class="im im-youtube"></i></a>
                                    </li>
                                {% endif %}



                                {% if profile.social_website %}
                                    <li>
                                        <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                                    </li>
                                {% endif %}
                            </ul>
                            {% if request.user.profile != profile %}
                            <a href="{% url 'send_message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="column column--2of3">
                    <div class="devInfo">
                        <h3 class="devInfo__title">About Me</h3>
                        <p class="devInfo__about">
                            {{ profile.bio }}
                        </p>
                    </div>
                    <div class="devInfo">
                        {% if top_skills or other_skills %}
                            <h3 class="devInfo__title">Skills</h3>
                        {% endif %}
                        <div class="devInfo__skills">
                            {% for skill in top_skills %}
                                <div class="devSkill">
                                    <h4 class="devSkill__title">{{ skill }}</h4>
                                    <p class="devSkill__info">
                                        {{ skill.description }}
                                    </p>
                                </div>
                            {% endfor %}
                            {% if other_skills %}
                                {% if top_skills %}
                                    <h3 class="devInfo__subtitle">Other Skills</h3>
                                {% endif %}
                                <div class="devInfo__otherSkills">
                                {% for skill in other_skills %}
                                    <span class="tag tag--pill tag--sub tag--lg">
                                  <small>{{ skill }}</small>
                                </span>
                                {% endfor %}
                            {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="devInfo">
                        {% if profile.project_set.all %}
                            <h3 class="devInfo__title">Projects</h3>
                        {% endif %}
                        <div class="grid grid--two">

                            {% for project in profile.project_set.all %}
                                <div class="column">
                                    <div class="card project">
                                        <a href="{% url 'project' project.id %}" class="project">
                                            <img class="project__thumbnail" src="{{ project.featured_image.url }}"
                                                 alt="{{ project.title }}"/>
                                            <div class="card__body">
                                                <h3 class="project__title">{{ project.title }}</h3>
                                                <p><a class="project__author" href="#">{{ project.owner.name }}</a>
                                                </p>
                                                <p class="project--rating">
                                                    <span style="font-weight: bold;">{{ project.vote_ratio }}%</span>
                                                    Positive
                                                    Feedback ({{ project.vote_total }}
                                                    Vote{{ project.vote_total|pluralize:'s' }})
                                                </p>
                                                <div class="project__tags">
                                                    {% for skill in project.tags.all|slice:'5' %}
                                                        <span class="tag tag--pill tag--main">
                                                      <small>{{ skill.name }}</small>
                                                    </span>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}